In [1]:
import numpy as np


In [4]:
s1=np.array([2,3,4])

In [5]:
s1

array([2, 3, 4])

In [6]:
s1.ndim

1

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.arange(1,10,3
         )

array([1, 4, 7])